image:
  repository: eu.gcr.io/gardener-project/gardener/extensions/registry-cache
  tag: latest
  pullPolicy: IfNotPresent

leaderElection:
  resourceLock: leases

resources: {}

vpa:
  enabled: true
  # resourcePolicy:
  #   minAllowed:
  #     cpu: 100m
  #     memory: 128Mi
  updatePolicy:
    updateMode: "Auto"

controllers:
  concurrentSyncs: 5
  ignoreOperationAnnotation: false
  healthcheck:
    concurrentSyncs: 5

registryConfig:
  registries:
    - ...

disableControllers: []

# imageVectorOverwrite: |
#   images:
#     - name: registry
#       sourceRepository: github.com/distribution/distribution
#       repository: registry
#       tag: "2.8.1"

gardener:
  version: ""
